### ISSUE TITLE
Comment / Uncomment should be using '!-- ' instead of '!--'

### ISSUE THREAD

**Issue by falkoner** [witspirit/IntelliJBehave#31]
I'm using latest plugin version 1.52. The feature "Comment/uncomment lines in story files" has and issue: when I press "comment" on a scenario line, IDE prepends line with  "!--" sequence. Jbehave (4.0.1) does not consider it as a token since it's not separated by space from the rest of the line, so it 1) indicates this line as Pending instead of Skipped and also 2) considers it to be continuation of previous line, marking it as Pending as well.

Expected: insert and delete "!-- " on comment/uncomment.

**Comment by Iurii-Dziuban** [comment]
voting up to fix it!

**Comment by ychulovskyy** [comment]
+1

**Comment by ulmanA** [comment]
+1
voting up to fix it too

**Comment by Shnitzelil** [comment]
voting up to fix it!

**Comment by harley84** [comment]
Will release soon.
@debritod, I see that you've had a great progress in your fork, would you like to create a pull request if it's stable?

**Comment by debritod** [comment]
I'm working on a different project, now. Maybe I can find time this week.

**Comment by benheap** [comment]
Can I ask what changes/improvements to expect from this?

**Comment by debritod** [comment]
Sorry for late response, lots of meetings this week.
As far as I can recall from my memory, I did following:
1. Reworked lexer and bnf. I threw some stuff away and I implemented some things for our companys needs.
2. implemented/changed References
3. changed Annotator
4. implemented Folding
5. implemented Higlighter
6. implemented Refactory
7. implemented StructureView
8. implemented Completion
9. implemented Commenter
10. moved stuff from CodeInspector to Resolver(?)
11. started to rework Token stuff (removing WeightChain because it doesn't work properly)

As far as I remember, I started doing point 11, but I am far away from finishing it.

**Comment by benheap** [comment]
Would you be happy to send me a copy of your forked plugin in it’s released form and I can provide extra feedback on the changes?

**Comment by debritod** [comment]
How? My Outlook crashes, when I try to send you a zip-file.

**Comment by debritod** [comment]
OK it seems I could send it to you.

**Comment by debritod** [comment]
Hi

Maybe it works now.

dinis

**Comment by JenoDK** [comment]
merged into master and preset in version v1.53
