### ISSUE TITLE
Change file extension in settings.

### ISSUE THREAD

**Issue by JSlain** [witspirit/IntelliJBehave#49]
All our story files have the extension `.feature`.
This plugins simply doesn't work for us, and i think that's a trivial fix to implement.

**Comment by JenoDK** [comment]
Hi @JSlain 

Can I ask what the reason is for not using the `.story` extension?
I don't have a lot of time currently to work on this plugin, feel free to have a look for youself.
See the [readme](https://github.com/witspirit/IntelliJBehave/blob/master/README.md) **contribute** section to set up the development environment.

**Comment by JSlain** [comment]
Not sure why... but we have tons of them, and using an IDE plugin wouldn't be a sufficient argument to rename all of them.
I know nothing about IntelliJ plugins, but i guess it's not black magic.
I'll give it a try.

**Comment by JSlain** [comment]
I just discovered this feature is already built-in into IntelliJ

![image](https://user-images.githubusercontent.com/986798/55733187-6351c280-59eb-11e9-81b0-a1b62a5f3d53.png)

**Comment by JenoDK** [comment]
Aha, good to hear. IntelliJ truely is wonderful :)
